version: 0.1.0
spec:
  units:
    - unit: &unitPort
        name: "port"
        regex: "^([0-9]{1,4}|[1-5][0-9]{4}|6[0-4][0-9]{3}|65[0-4][0-9]{2}|655[0-2][0-9]|6553[0-5])$"

properties:
  - property: &nifiWebHttpPort
      propertyNames:
        - name: "nifi.web.http.port"
          kind:
            type: "file"
            file: "nifi.properties"
      datatype:
        type: "integer"
        min: "1"
        max: "65535"
        unit: *unitPort
      defaultValues:
        - fromVersion: "0.0.0"
          value: "8080"
      roles:
        - name: "node"
          required: true
      asOfVersion: "0.0.0"
      description: "Start the NiFi node web ui on a different port (default: 8080)"

  - property: &nifiClusterNodeProtocolPort
      propertyNames:
        - name: "nifi.cluster.node.protocol.port"
          kind:
            type: "file"
            file: "nifi.properties"
      datatype:
        type: "integer"
        min: "1"
        max: "65535"
        unit: *unitPort
      roles:
        - name: "node"
          required: true
      asOfVersion: "0.0.0"
      description: "Node protocol port. Only set in cluster mode. No default."

  - property: &nifiClusterLoadBalancePort
      propertyNames:
        - name: "nifi.cluster.load.balance.port"
          kind:
            type: "file"
            file: "nifi.properties"
      datatype:
        type: "integer"
        min: "1"
        max: "65535"
        unit: *unitPort
      defaultValues:
        - fromVersion: "0.0.0"
          value: "6342"
      roles:
        - name: "node"
          required: true
      asOfVersion: "0.0.0"
      description: "Load balancing port. Only set in cluster mode (default: 6342)."