[package]
authors = ["Stackable GmbH <info@stackable.de>"]
description = "Contains the Apache NiFi CRD structs and utilities"
edition = "2021"
license = "OSL-3.0"
name = "stackable-nifi-crd"
repository = "https://github.com/stackabletech/nifi-operator"
version = "0.5.0-nightly"

[dependencies]
xml-rs = "0.8"
serde = "1.0"
serde_json = "1.0"
snafu = "0.6"
stackable-operator = { git = "https://github.com/stackabletech/operator-rs.git", tag = "0.8.0" }
strum = { version = "0.23", features = ["derive"] }
strum_macros = "0.23"


