[package]
authors = ["Malte Sander <malte.sander.it@gmail.com>"]
description = "Contains the Apache NiFi CRD structs and utilities"
edition = "2018"
license = "OSL-3.0"
name = "stackable-nifi-crd"
repository = "https://github.com/stackabletech/nifi-operator"
version = "0.3.0"

[dependencies]
stackable-operator = { git = "https://github.com/stackabletech/operator-rs.git", tag = "0.3.0" }
stackable-zookeeper-crd = { git = "https://github.com/stackabletech/zookeeper-operator.git", tag = "0.4.1" }

semver = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
strum = "0.21"
strum_macros = "0.21"

[dev-dependencies]
k8s-openapi = { version = "0.13", default-features = false, features = ["v1_22"] }

[features]
default = ["native-tls"]
native-tls = ["stackable-operator/native-tls"]
rustls-tls = ["stackable-operator/rustls-tls"]
