---
apiVersion: v2
name: nifi-operator
version: "0.6.0"
appVersion: "0.6.0"
description: The Stackable Operator for Apache NiFi
home: https://github.com/stackabletech/nifi-operator
maintainers:
  - name: Stackable
    url: https://www.stackable.tech
